oj_django_project/oj_django_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('problems.urls'))
]

oj_django_project/problems/urls.py
from django.urls import path
from . import views 

app_name = 'problems'

urlpatterns = [
    path('', views.index, name='index'),
    path('problem/<int:problem_id>', views.detail_submit, name='detail_submit_path'),
    path('submissions/<int:problem_id>', views.submissions_detail, name='submissions_detail_path'),
    
    path('profile/<str:username>', views.user_profile, name='user_profile_path'),
    
    path('submit/', views.submit, name='submit_path'), # for the post request

    ## Auth urls
    path('login_page/', views.login_page, name='login_page_path'),
    path('signup_page/', views.signup_page, name='signup_page_path'),
    
    ## Auth actions urls for post request
    path('login_action', views.login_action, name='login_action_path'),
    path('signup_action', views.signup_action, name='signup_action_path'),
    path('logout_action', views.logout_action, name='logout_action_path'),
]

oj_django_project/problems/models.py
from django.db import models
from django.contrib.auth.models import User

from .backend.utils import Logger

# Create your models here.

# Todo : Add Proper contraints

"""
Fields 
id (default) ,
name,
data_dir_path,
difficulty,
num_testcases,
time_limit : floating point, unit : second
"""
class Problem(models.Model) :
    name = models.CharField(max_length=200)
    data_dir_path = models.CharField(max_length=200)
    difficulty = models.IntegerField()
    num_testcases = models.IntegerField()
    time_limit = models.FloatField(default=1)

"""
id : int, primary key
problem_id : int foreign key
source_file_path : string
verdict : string,
verdict_type : 0 -> AC, 1 -> WA, 2 -> RE, 3 -> TLE, 4 -> MLE, 5 -> CE
verdict_type : -1 -> Not Logged In  (this is just for submit buttton, never saved in database)
runtime : int, (in msec)
language_id : int 
submission_time : timestamp

"""
class Submission(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    source_file_path = models.CharField(max_length=200)
    verdict = models.CharField(max_length=50) # Time Limit Exceeded on Test Case 1000 (37 chars)
    verdict_type = models.IntegerField()
    runtime = models.IntegerField()
    language_id = models.IntegerField()
    submission_time = models.DateTimeField()


"""
user,

first name and last name are redundant here
might going to be removed

first_name, 
last_name,
num_problems_solved : integer 
score : integer,
"""
class UserInfo(models.Model) :
    user = models.ForeignKey(User, on_delete=models.CASCADE, unique=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    num_problems_solved = models.IntegerField()
    score = models.IntegerField()

    def get_full_name(self) -> str :
        return self.first_name + " " + self.last_name
    
    # Make sure it works
    def function1(self):
        pass

    def add_num_problems_solved(self):
        self.num_problems_solved += 1
        self.save()


    # return id 
    # return -1 if there was error
    @staticmethod
    def create_userinfo(user, first_name:str='', last_name:str='', num_problems_solved:int=0, score:int=0) :
        userinfo_obj = UserInfo(
            user                = user                ,
            first_name          = first_name          ,
            last_name           = last_name           ,
            num_problems_solved = num_problems_solved ,
            score               = score               ,
        )
        userinfo_obj.save()
    
    def get_num_problems_solved(user)->int:
        return UserInfo.objects.get(user=user).num_problems_solved 
    
    # Todo : make user public, private info fucntions here
    def get_user_public_info(user):
        pass

"""
status : 1 -> attempted, 2 -> solved 
"""
class UserProblemRelation(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    status = models.IntegerField()

    @staticmethod
    def add_attempted(user, problem):
        # check if already attempted, or solved
        Logger.log("add_attempted() for user = " + str(user) + "problem = " + str(problem))
        qset = UserProblemRelation.objects.filter(user=user).filter(problem=problem)

        if qset.exists() : 
            Logger.log("Already Attempted")
            # Todo May remvoe this.
            assert qset[0].status == 1 or qset[0].status == 2
            # do nothing
            pass
        else :
            Logger.log("Adding as Attempted")
            upr_obj = UserProblemRelation(user=user, problem=problem, status=1)
            upr_obj.save()

    @staticmethod
    def add_solved(user, problem):
        Logger.log("add_solved() for user = " + str(user) + "problem = " + str(problem))
        
        try:
            upr_obj = UserProblemRelation.objects.get(user=user, problem=problem)
            # query set's save doesnt works
            # qset[0].save()

            if upr_obj.status == 1:
                Logger.log("Already Attempted. Adding as Solved")
                upr_obj.status = 2
                upr_obj.save()
                # add num_solved in userinfo
                UserInfo.objects.get(user=user).add_num_problems_solved()
            else:
                Logger.log("Already Solved")

        except UserProblemRelation.DoesNotExist :
            Logger.log("Adding as Solved")
            upr_obj = UserProblemRelation(user=user, problem=problem, status=2)
            upr_obj.save()
            # add num_solved in userinfo
            UserInfo.objects.get(user=user).add_num_problems_solved()
            #upr_obj.user.num_problems_solved += 1
            #upr_obj.user.save()


"""
id,
name
"""
class Language(models.Model) :
    name = models.CharField(max_length=30)

"""
problem_id,
language_id
"""

class ProblemLanguageRelation(models.Model) :
    problem = models.ForeignKey(Problem, on_delete=models.CASCADE)
    language_id = models.IntegerField()


    

oj_django_project/problems/views.py
import json
from django.http import HttpResponse, JsonResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse

from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate


from .backend import configs
from .models import Problem, UserInfo, Language
from .backend.utils import Logger
from .backend.core import SubmissionHandler
from .backend.configs import cur_config


def index(request):
    Logger.log('Index page requested')

    # merging the two dictionaries by using |
    context = {'problem_list': Problem.objects.all(), **get_cur_user_context(request) }
    
    return render(request, 'problems/index.html', context)


def detail_submit(request, problem_id):
    problem = get_object_or_404(Problem, pk=problem_id)

    # merging the two dictionaries by using |
    context = { **get_problem_detailed_context(problem) , **get_cur_user_context(request) } 

    return render(request, 'problems/detail_submit.html', context)


def submissions_detail(request, problem_id):
    # all submission with that problem id 
    problem = get_object_or_404(Problem, pk=problem_id)

    # merging the two dictionaries by using |
    context = {'problem': problem, **get_cur_user_context(request) }

    return render(request, 'problems/submissions_detail.html', context)



@csrf_exempt
def submit(request):
    if request.method != 'POST':
        return HttpResponse("This endpoint is only for code submission. Use POST request only.")
    
    user = get_cur_user_obj(request)
    if user is None:
        # Not logged in.
        return JsonResponse({
            'verdict': 'Please Login to Submit code.',
            'verdict_type' : -1
        })        

    # request body contain code, and language and problem id
    req_body = request.body

    #print(req_body)

    body = json.loads(req_body, strict=False)
    problem_id = int(body['problem_id'])
    language_id = int(body['language_id'])
    code = body['code']

    Logger.log("(views.py)Received submission for P-" + str(problem_id)
               + " language_id " + str(language_id))

    verdict, verdict_type, verdict_details = SubmissionHandler.submit(code, user, problem_id, language_id)

    verdict_dict = dict({
        'verdict': verdict,
        'verdict_type' : verdict_type,
        'verdict_details' : verdict_details
    })

    return JsonResponse(verdict_dict)

# Todo : Move code to functions, modularize it
# View for profile
def user_profile(request, username):
    user = get_user_obj(username)
    if user is None:
        # 404 page
        return render(request, 'problems/404.html')
    else:
        is_requested_user_logged_in = is_user_logged_in(request, username)
        user_private_info = None 
        if is_requested_user_logged_in :
            user_private_info = get_user_private_info(user)

        context = {
            'user_public_info' : get_user_public_info(user),
            'is_requested_user_logged_in' : is_requested_user_logged_in,
            'user_private_info' : user_private_info,
            **get_cur_user_context(request),
            
        }
        return render(request, 'problems/profile.html', context)


# next_page_field_name = 'next'

# cant use reverse globally
# default_next_page = reverse('problems:index')

# Todo Test if works
default_next_page = '/'

## User Auth related views : 

def login_page(request, error_message : str = ''):
    next_page = get_next_page(request)
    context = get_login_page_context(next_page, error_message)
    return render(request, 'problems/login.html', context)

# for post request of login
def login_action(request):

    Logger.log("login action initialted")
    error_message = ''
    next_page = get_next_page(request)

    try:
        username = request.POST['username-input']
        password = request.POST['password-input']

        user_obj_qset = User.objects.filter(username=username)

        if not user_obj_qset.exists() : 
            error_message = "No user with username - " + username
        else :
            log = ""
            user_obj = user_obj_qset[0]

            if user_obj.is_authenticated :
                log += "Given user is Already authenticated .\n"

            user = authenticate(username=username, password=password)

            if user is None :
                log += "Given password is wrong\n"
                error_message = "Wrong Password"
                Logger.log(log)
            else :
                log += "Successfully authenticated\n"
                # just sets the cookie
                login(request, user)
                log += "Successfully logged in .\n"
                Logger.log(log)
                # we are done here. Now redirect

                return HttpResponseRedirect(next_page)

    except KeyError:
        print("KeyError")
        error_message = 'KeyError in form. Invalid form input field names'
        
    Logger.log("!!!!! Error Message : " + error_message)

    return login_page(request, error_message)

# for post request of signup
def signup_action(request):

    Logger.log("signup action initialted")
    
    error_message = ''
    next_page = get_next_page(request)

    try:
        username = request.POST['username-input']
        email = request.POST['email-input']
        password = request.POST['password-input']
        re_password = request.POST['re-enter-password-input']

        user_obj_qset = User.objects.filter(username=username)

        if user_obj_qset.exists() : 
            error_message = "There are existing user with username - " + username
        elif password != re_password:
            error_message = "Password dont match" 
        # no need to check for email validation
        else :
            log = ""
            # create user
            new_user = User.objects.create_user(username, email, password)
            new_user.save()

            # create userinfo
            UserInfo.create_userinfo(new_user)

            log += "Created User and UserInfo object\n"
            authenticate(username=username, password=password)
            login(request, new_user)
            log += "Loggin In the user\n" 
            log += "Signup of username - " + username + " Completed\n"
            Logger.log(log)
            return HttpResponseRedirect(next_page)

    except KeyError:
        print("KeyError")
        error_message = 'KeyError in form. Invalid form input field names'
        
    Logger.log("!!!!! Error Message : " + error_message)

    return signup_page(request, error_message)

def signup_page(request, error_message : str = ''):
    next_page = get_next_page(request)
    context = get_signup_page_context(next_page, error_message)
    return render(request, 'problems/signup.html', context)


def logout_action(request):
    next_page = get_next_page(request)
    logout(request)
    return HttpResponseRedirect(next_page)


## Utility Code : Later, move them to seperate file

def get_login_page_context(next_page : str, error_message : str=''):
    post_url = reverse('problems:login_action_path') + '?next=' + next_page
    return get_form_page_context(post_url, error_message)

def get_signup_page_context(next_page : str, error_message : str=''):
    post_url = reverse('problems:signup_action_path') + '?next=' + next_page
    return get_form_page_context(post_url, error_message)

def get_form_page_context(post_url:str, error_message : str=''):
    form_input_error = False

    if error_message != '' :
        form_input_error = True
    
    context = {
        'post_url':post_url,
        'form_input_error' : form_input_error,
        'error_message' : error_message
    }
    return context


def get_next_page(request):
    try:
        return request.GET['next']
    except KeyError:
        Logger.log("KeyError in get_next_page")
        return default_next_page

class UserPublicInfo:
    
    def __init__(self):
        self.is_valid = False

    def __init__(self,
        username            ,
        full_name           ,
        num_problems_solved ,
    ):
        self.is_valid             = True            
        self.username             = username            
        self.full_name            = full_name           
        self.num_problems_solved  = num_problems_solved 
    

class UserPrivateInfo:
    def __init__(self,
        email
    ):
        self.email = email

def get_cur_user_obj(request):
    if not is_cur_user_logged_in(request):
        return None 
    else:
        # Still may return none.
        return get_user_obj(request.user.username)

def get_user_obj(username : str):
    user_qset = User.objects.filter(username=username)

    if user_qset.exists() :
        return user_qset[0]
    else:
        return None

def get_user_public_info(user_obj) -> UserPublicInfo:
    username = user_obj.username
    full_name = user_obj.first_name + configs.SPACE + user_obj.last_name
    num_problems_solved = UserInfo.get_num_problems_solved(user_obj)
    return UserPublicInfo(username, full_name, num_problems_solved)

def get_user_private_info(user_obj) -> UserPrivateInfo:
    email = user_obj.email 
    return UserPrivateInfo(email)

def is_user_logged_in(request, username):
    # Todo : Find out what user.is_active means
    if not is_cur_user_logged_in(request) :
        return False
    else :
        return request.user.username == username 

def get_cur_user_context(request):
    is_logged_in = True
    username = ''

    if not is_cur_user_logged_in(request) :
        is_logged_in = False
    else :
        username = request.user.username
    return {
        'is_logged_in' : is_logged_in,
        'username' : username,
    }

def is_cur_user_logged_in(request):
    return request.user.is_authenticated

"""
absolute path = "C:\\....\data\problems_data"
data_dir_path = "\1"

/desc.txt : description of the file

oj_django_project/problems/templates/problems/base.html
<!--
    required context (base.html)

    is_logged_in : bool
    username : string

-->

<!DOCTYPE html>
<html>
    <head>
        {% block title%}
        <title>Codesmed</title>
        {% endblock title %}

        {% load static %}

        {% block static_loads %}
        <link rel="shortcut icon" type="image/png" href="https://oj-r1pi.onrender.com/static/problems/favicon.ico"/>
        <link rel="stylesheet" type="text/css" href="https://oj-r1pi.onrender.com/static/problems/common.css"/>
        {% endblock static_loads %}

    </head>
    <body>

        {% block header_root %}
        <div id="header-root">
            <div id="main-heading">
                <a href="{% url 'problems:index' %}" id="title-link" 
                class="invisible-link white-text styled-text">
                    Codesmed
                </a>
            </div>
            <div id="user-profile-heading">
                {% if is_logged_in %}
                <a href = "{% url 'problems:user_profile_path' username %}" class="white-text styled-text"> Profile </a>
                {% else %}
                <a href="{% url 'problems:login_page_path' %}" class="white-text styled-text"> Login </a>
                {% endif %}
            </div>
        </div>
        {% endblock header_root %}

        {% block content_root %}
        {% endblock content_root %}
    </body>
</html>

oj_django_project/problems/templates/problems/detail.html
<!--
    required context 

    'problem' :  Problem object ,
    'description' 
    'input' 
    'output'
    'constraint'
    'example' : array of dict like 
    
    'languages_str' : string representation of array of languages as strings

-->

<!DOCTYPE html>
<html>
    <head>
        <title>Problems-{{problem.id}}</title>
        {% load static %}
        <link rel="shortcut icon" type="image/png" href="{% static '/problems/images/favicon.ico' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/problems/styles/common.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static '/problems/styles/problem_detail.css' %}"/>
    </head>
    <body>
        <div id="header-root">
            <h1>
                <a href="{% url 'problems:index' %}" id="title-link" class="invisible-link">
                    Codesmed
                </a>
            </h1>
        </div>
        <div id="content-root">
            <div id="problem-header">
                <div class="problem-title">
                    <h2 class="heading2">P{{problem.id}} {{problem.name}}</h2>
                </div>
                <div class="problem-header-control">
                    <a href="{% url 'problems:submit_page_path' problem.id %}" class="button-link" >
                        Submit
                    </a>
                    <a href="{% url 'problems:submissions_detail_path' problem.id %}" class="button-link" >
                        View All Submissions
                    </a>
                </div>
            </div>
            <div id="problem-detail">
                <div id="problem-desc">
                    <p>{{description|linebreaksbr}}</p>
                </div>
                <div id="problem-inp">
                    <h3>Input : </h3>
                    <p>{{input|linebreaksbr}}</p>
                </div>
                <div id="problem-out">
                    <h3>Output : </h3>
                    <p>{{output|linebreaksbr}}</p>
                </div>
                <div id="problem-constraints">
                    <h3>Constraints : </h3>
                    <p>{{constraints|linebreaksbr}}</p>
                </div>
                <div id="problem-languages">
                    <br />
                    <p><strong>Languages Supported :</strong> {{languages_str}}</p>
                </div>
                <div id="problem-examples">
                    <h3>Sample I/O examples : </h3>
                    <p>{{examples|linebreaksbr}}</p>
                </div>
            </div>
        </div>
    </body>
</html>

oj_django_project/problems/templates/problems/detail_submit.html
<!--
    required context (base.html)

    is_logged_in : bool
    username : string

    required context apart from base.html

    'problem' :  Problem object ,
    'description' 
    'input' 
    'output'
    'constraint'
    'example' : array of dict like 
    
    'languages_str' : string representation of array of languages as strings
    
    'languages' : array of Language objects 

--> 

{% extends "problems/base.html" %}


{% block title%}
<title>Problems-{{problem.id}}</title>
{% endblock title %}

{% load static %}
{% block static_loads %}
<link rel="shortcut icon" type="image/png" href="https://oj-r1pi.onrender.com/static/problems/favicon.ico"/>
<link rel="stylesheet" type="text/css" href="https://oj-r1pi.onrender.com/static/problems/common.css"/>
<link rel="stylesheet" type="text/css" href="https://oj-r1pi.onrender.com/static/problems/problem_detail.css"/>
{% endblock static_loads %}


{% block content_root %}

<div id="content-root">

<h2 class="heading2">P{{problem.id}} {{problem.name}}</h2>

<div id="detail-submit-content-root">

    <div id="problem-detail-root" class="main-column">
        <div id="problem-header">
            
            <div class="problem-header-control">
                <a href="{% url 'problems:submissions_detail_path' problem.id %}" class="button-link" >
                    View All Submissions
                </a>
            </div>
        </div>
        <div id="problem-detail">
            <div id="problem-desc">
                <p>{{description|linebreaksbr}}</p>
            </div>
            <div id="problem-inp">
                <h3>Input : </h3>
                <p>{{input|linebreaksbr}}</p>
            </div>
            <div id="problem-out">
                <h3>Output : </h3>
                <p>{{output|linebreaksbr}}</p>
            </div>
            <div id="problem-constraints">
                <h3>Constraints : </h3>
                <p>{{constraints|linebreaksbr}}</p>
                <br/>
                <p>Time Limit : {{problem.time_limit}}sec</p>
            </div>
            <div id="problem-languages">
                <br />
                <p><strong>Languages Supported :</strong> {{languages_str}}</p>
            </div>
            <div id="problem-examples">
                <h3>Sample I/O examples : </h3>
                <p>{{examples|linebreaksbr}}</p>
            </div>
        </div>
    </div>

    <div id="problem-submit-root" class="main-column">
        <div id="submission-input">
            <form>
            <textarea id="submission-input-textarea" name="input-code" rows="25" cols="100" maxlength="50000"></textarea>
            <br />
            <select id="language-selector-list" name="language-selector">
            {% for language in languages %}
                <option class="language-selector-option" value="{{language.id}}">
                    {{language.name}}
                </option>    
            {% endfor %}
            </select>
            <input type="button" onClick="handleSubmit()" value="Submit" class="code-submit-button"/>
            </form>
        </div>
        <hr />
        <div id="verdict">
            <span>Verdict : </span>
            <span id="verdict-element">No code submitted.</span>
            <img src= "https://oj-r1pi.onrender.com/static/problems/loading_1.gif" id="verdict-loading-gif"
            alt="loading gif" hieght="15" width="15"/>
        </div>
    </div>

</div>
</div>
<script>
    const cur_page_problem_id = {{problem.id}} ;
</script>
<script src="https://oj-r1pi.onrender.com/static/problems/submit_handling.js"></script>
<script src="https://oj-r1pi.onrender.com/static/problems/test.js"></script>


{% endblock content_root %}

 

oj_django_project/problems/templates/problems/index.html
<!--
    required context (base.html)

    is_logged_in : bool
    username : string

    required context apart from base.html

    problems_list : an QuerySet of Problem

-->

{% extends "problems/base.html" %}


{% block title%}
<title>Codesmed - Problemset</title>
{% endblock title %}

{% block content_root %}
<div id="content-root">
    <h2 class="heading2">Problemset</h2>
    <table class="fancy-table-1">
        
        <tbody>
            <tr>
                <td class="table-header-cell">ID</td>
                <td class="table-header-cell">Problem Name</td>
                <td class="table-header-cell">Difficulty</td>
            </tr>
        {% for problem in problem_list %}
        <tr id="problem-{{problem.id}}">
            <td>{{problem.id}}</td>
            <td>
                <a href="{% url 'problems:detail_submit_path' problem.id %}" class="">{{problem.name}}</a>
            </td>
            <td>{{problem.difficulty}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <div id="notice-board">
        <h2 class="heading2">Notice Board</h2>
        
        <p>For now database is not persistent. All submmission data, user data is lost on server restart.</p>
        <p>Now you can use <span>ONLINE_JUDGE</span> macro in your c++ code.</p>
        <p>Now server can detect TLE and MLE verdict.</p>
        <p>Memory Limit is by default 256MB for now.</p>
    </div>
</div>
{% endblock content_root %}

oj_django_project/problems/templates/problems/login.html
<!--
    required context 

    post_url : string
    form_input_error : bool
    error_message : string

-->

{% extends "problems/base.html" %}


{% block title%}
<title>Codesmed - Login Page </title>
{% endblock title %}

{% block header_root %}
<div id="header-root">
    <div id="main-heading">
        <a href="{% url 'problems:index' %}" id="title-link" 
        class="invisible-link white-text styled-text">
            Codesmed
        </a>
    </div>
</div>
{% endblock header_root %}

{% block content_root %}
<div id="content-root">
<h2 class="heading2">Login Page</h2>
<form action="{{post_url}}" method="post" class="fancy-form-1">
    {% csrf_token %}
    <label for="username-input">Enter Username</label>
    <input type="text" name="username-input"></input>

    <br />

    <label for="password-input">Enter Password</label>
    <input type="password" name="password-input"></input>
    
    <br />
    
    {% if form_input_error %}
    <p>Error : {{error_message}}</p>
    {% endif %}
    <div class="submit-div">
        <input type="submit" value="Submit"></input>
    </div>
</form>
<div class="footer-button-div">
    Not having an account? 
    <a href="{% url 'problems:signup_page_path' %}" class="button-link" >Sign Up</a>
</div>
</div>
{% endblock content_root %}

oj_django_project/problems/templates/problems/profile.html
<!--
    required context (base.html)

    is_logged_in : bool (current user logged in or not)
    username : string (cur user who is logged in , or '' if not logged in)

    required context apart from base.html

    user_public_info : UserPublicInfo object  with these fields
        -> username : string 
        -> full_name : string
        -> num_problems_solved : int  
        -> problems_solved : list of problem objects, which this user has solved

    is_requested_user_logged_in : bool , is the user, whose page is this, is logged in 

    user_private_info : None if not logged in, else UserPrivateInfo object with these fields 
        -> email 

-->

{% extends "problems/base.html" %}


{% block title%}
<title>Codesmed - User {{user_public_info.username}}</title>
{% endblock title %}

{% block content_root %}
<div id="content-root">
    <table class="fancy-table-1">
        <tr>
            <td>Username</td> <td>{{user_public_info.username}}</td>
        </tr>
        <tr> 
            <td>Name</td><td>{{user_public_info.full_name}}</td>
        </tr>
        <tr>
            <td>Problems Solved</td><td>{{user_public_info.num_problems_solved}}</td>
        </tr>
        {% if is_requested_user_logged_in %}
        <tr>
            <td>Email(Only visible to you)</td><td>{{user_private_info.email}}</td>
        </tr>
        {% endif %}
    </table>

{% if is_requested_user_logged_in %}
<div class="footer-button-div">
<a href="{% url 'problems:logout_action_path' %}" class="button-link"> Logout </a>    
</div>
{% endif %}

</div>
{% endblock content_root %}

oj_django_project/problems/templates/problems/signup.html
<!--
    required context 
    post_url : string
    form_input_error : bool
    error_message : string

-->

{% extends "problems/base.html" %}


{% block title%}
<title>Codesmed - Signup Page </title>
{% endblock title %}

{% block header_root %}
<div id="header-root">
    <div id="main-heading">
        <a href="{% url 'problems:index' %}" id="title-link" 
        class="invisible-link white-text styled-text">
            Codesmed
        </a>
    </div>
</div>
{% endblock header_root %}


{% block content_root %}
<div id="content-root">
    <h2 class="heading2">SignUp Page</h2>
<form action="{{post_url}}" method="post" class="fancy-form-1">
    {% csrf_token %}
    <label for="username-input">Enter Username</label>
    <input type="text" name="username-input"></input>

    <br />

    <label for="email-input">Enter Email</label>
    <input type="email" name="email-input"></input>

    <br />

    <label for="password-input">Enter Password</label>
    <input type="password" name="password-input"></input>
    
    <br />

    <label for="re-enter-password-input">Re Enter Password</label>
    <input type="password" name="re-enter-password-input"></input>
    
    <br />
    
    {% if form_input_error %}
    <p>Error : {{error_message}}</p>
    {% endif %}

    <p>Remember Your Password, If you forgot it. You wont be able to reset it.</p>
    
    <div class="submit-div">
        <input type="submit" value="Submit"></input>
    </div>
</form>
</div>
{% endblock content_root %}

oj_django_project/problems/templates/problems/submissions_detail.html
<!--
    required context (base.html)

    is_logged_in : bool
    username : string

    required context apart from base.html

    problem : a Problem object

-->

{% extends "problems/base.html" %}


{% block title%}
<title>Submissions P-{{problem.id}}</title>
{% endblock title %}

{% block content_root %}
<div id="content-root">
    <h2 class="heading2">Submissions of 
        <a href="{% url 'problems:detail_submit_path' problem.id %}">
            P{{problem.id}} {{problem.name}}
        </a>
    </h2>
    <table class="fancy-table-1">
        
    <tbody>
        <tr>
            <td class="table-header-cell" >ID</td>
            <td class="table-header-cell" >User</td>
            <td class="table-header-cell" >Time of Submission</td>
            <td class="table-header-cell" >Runtime</td>
            <td class="table-header-cell" >Verdict</td>
        </tr>
        {% for submission in problem.submission_set.all %}
        <tr id="submission-{{submission.id}}">
            <td>{{submission.id}}</td>
            <td>
                <a href="{% url 'problems:user_profile_path' submission.user.username %}">{{submission.user.username}}</a>
            </td>
            <td>{{submission.submission_time}}</td>
            <td>{{submission.runtime}} ms</td>
            <td class="verdict-text-{{submission.verdict_type}}">{{submission.verdict}}</td>
        </tr>
        {% endfor %}
    </tbody>
    </table>
</div>
{% endblock content_root %}